application: psnserverapi
version: 7
runtime: python27
api_version: 1
threadsafe: true

inbound_services:
- warmup

builtins:
- remote_api: on
 
handlers:

- url: /.*
  script: PlaystationNetworkAPI_server.application
  
